### ISSUE TITLE
[RFT] aac5c57a-aa01-49bb-ad20-70536dd2907f | Cannot read property 'getObservationReadableValue' of undefined

### ISSUE THREAD

**Issue by arjunk** [avniproject/JSS-Singrauli#4]
Rule uuid : aac5c57a-aa01-49bb-ad20-70536dd2907f

[Metabase report link](https://reporting.avniproject.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6ImNhcmRfXzU0MiIsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsIm9yZ2FuaXNhdGlvbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIkpTUyBTaW5ncmF1bGkiXSxbIj0iLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJhYWM1YzU3YS1hYTAxLTQ5YmItYWQyMC03MDUzNmRkMjkwN2YiXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6NX0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6bnVsbCwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmllbGQiLCJvcmdhbmlzYXRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiY29sdW1ucyI6W10sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdXX0sInBpdm90X3RhYmxlLmNvbGxhcHNlZF9yb3dzIjp7InZhbHVlIjpbIltcIkpTU0NQXCJdIiwiW1wiSUhNUFwiXSIsIltcIkFQRiBPZGlzaGFcIl0iLCJbXCJBc2h3aW5pXCJdIiwiW1wiSk5QQ1RcIl0iLCJbXCJMZW5kLWEtaGFuZC1pbmRpYSBVQVRcIl0iLCJbXCJJUEggTURBVCBUcmlhbFwiXSIsIltcIklITVAgVFJBSU5JTkdcIl0iLCJbXCJTYWtoaSBBcHBcIl0iXSwicm93cyI6W1siZmllbGQiLCJvcmdhbmlzYXRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXX19LCJvcmlnaW5hbF9jYXJkX2lkIjoyNzIzfQ==)

Current count : 3

**Comment by BEULAHEVANJALIN** [comment]
Same as #5
